test:
  host: localhost
  database: <%= ENV['MONGOID_DATABASE'] || 'quby_mongoid_test' %>
  autocreate_indexes: true
  persist_in_safe_mode: true
  sessions:
    default:
      database: <%= ENV['MONGOID_DATABASE'] || 'quby_mongoid_test' %>
      hosts:
        - localhost:27017
